# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ms/elec/birdscanner/nrf52-ao

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ms/elec/birdscanner/nrf52-ao

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ms/elec/birdscanner/nrf52-ao/CMakeFiles /Users/ms/elec/birdscanner/nrf52-ao//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ms/elec/birdscanner/nrf52-ao/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/ms/elec/birdscanner/nrf52-ao/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nrf52-ao.elf

# Build rule for target.
nrf52-ao.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nrf52-ao.elf
.PHONY : nrf52-ao.elf

# fast build rule for target.
nrf52-ao.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/build
.PHONY : nrf52-ao.elf/fast

#=============================================================================
# Target rules for targets named rust_app_build

# Build rule for target.
rust_app_build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rust_app_build
.PHONY : rust_app_build

# fast build rule for target.
rust_app_build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rust_app_build.dir/build.make CMakeFiles/rust_app_build.dir/build
.PHONY : rust_app_build/fast

c/src/hw_egu.obj: c/src/hw_egu.c.obj
.PHONY : c/src/hw_egu.obj

# target to build an object file
c/src/hw_egu.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/hw_egu.c.obj
.PHONY : c/src/hw_egu.c.obj

c/src/hw_egu.i: c/src/hw_egu.c.i
.PHONY : c/src/hw_egu.i

# target to preprocess a source file
c/src/hw_egu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/hw_egu.c.i
.PHONY : c/src/hw_egu.c.i

c/src/hw_egu.s: c/src/hw_egu.c.s
.PHONY : c/src/hw_egu.s

# target to generate assembly for a file
c/src/hw_egu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/hw_egu.c.s
.PHONY : c/src/hw_egu.c.s

c/src/hw_gpio.obj: c/src/hw_gpio.c.obj
.PHONY : c/src/hw_gpio.obj

# target to build an object file
c/src/hw_gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/hw_gpio.c.obj
.PHONY : c/src/hw_gpio.c.obj

c/src/hw_gpio.i: c/src/hw_gpio.c.i
.PHONY : c/src/hw_gpio.i

# target to preprocess a source file
c/src/hw_gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/hw_gpio.c.i
.PHONY : c/src/hw_gpio.c.i

c/src/hw_gpio.s: c/src/hw_gpio.c.s
.PHONY : c/src/hw_gpio.s

# target to generate assembly for a file
c/src/hw_gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/hw_gpio.c.s
.PHONY : c/src/hw_gpio.c.s

c/src/hw_timer.obj: c/src/hw_timer.c.obj
.PHONY : c/src/hw_timer.obj

# target to build an object file
c/src/hw_timer.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/hw_timer.c.obj
.PHONY : c/src/hw_timer.c.obj

c/src/hw_timer.i: c/src/hw_timer.c.i
.PHONY : c/src/hw_timer.i

# target to preprocess a source file
c/src/hw_timer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/hw_timer.c.i
.PHONY : c/src/hw_timer.c.i

c/src/hw_timer.s: c/src/hw_timer.c.s
.PHONY : c/src/hw_timer.s

# target to generate assembly for a file
c/src/hw_timer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/hw_timer.c.s
.PHONY : c/src/hw_timer.c.s

c/src/isr_mask.obj: c/src/isr_mask.c.obj
.PHONY : c/src/isr_mask.obj

# target to build an object file
c/src/isr_mask.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/isr_mask.c.obj
.PHONY : c/src/isr_mask.c.obj

c/src/isr_mask.i: c/src/isr_mask.c.i
.PHONY : c/src/isr_mask.i

# target to preprocess a source file
c/src/isr_mask.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/isr_mask.c.i
.PHONY : c/src/isr_mask.c.i

c/src/isr_mask.s: c/src/isr_mask.c.s
.PHONY : c/src/isr_mask.s

# target to generate assembly for a file
c/src/isr_mask.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/isr_mask.c.s
.PHONY : c/src/isr_mask.c.s

c/src/main.obj: c/src/main.c.obj
.PHONY : c/src/main.obj

# target to build an object file
c/src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/main.c.obj
.PHONY : c/src/main.c.obj

c/src/main.i: c/src/main.c.i
.PHONY : c/src/main.i

# target to preprocess a source file
c/src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/main.c.i
.PHONY : c/src/main.c.i

c/src/main.s: c/src/main.c.s
.PHONY : c/src/main.s

# target to generate assembly for a file
c/src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/c/src/main.c.s
.PHONY : c/src/main.c.s

vendor/nrfx/bsp/stable/mdk/gcc_startup_nrf52840.obj: vendor/nrfx/bsp/stable/mdk/gcc_startup_nrf52840.S.obj
.PHONY : vendor/nrfx/bsp/stable/mdk/gcc_startup_nrf52840.obj

# target to build an object file
vendor/nrfx/bsp/stable/mdk/gcc_startup_nrf52840.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/vendor/nrfx/bsp/stable/mdk/gcc_startup_nrf52840.S.obj
.PHONY : vendor/nrfx/bsp/stable/mdk/gcc_startup_nrf52840.S.obj

vendor/nrfx/bsp/stable/mdk/system_nrf52840.obj: vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.obj
.PHONY : vendor/nrfx/bsp/stable/mdk/system_nrf52840.obj

# target to build an object file
vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.obj
.PHONY : vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.obj

vendor/nrfx/bsp/stable/mdk/system_nrf52840.i: vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.i
.PHONY : vendor/nrfx/bsp/stable/mdk/system_nrf52840.i

# target to preprocess a source file
vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.i
.PHONY : vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.i

vendor/nrfx/bsp/stable/mdk/system_nrf52840.s: vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.s
.PHONY : vendor/nrfx/bsp/stable/mdk/system_nrf52840.s

# target to generate assembly for a file
vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.s
.PHONY : vendor/nrfx/bsp/stable/mdk/system_nrf52840.c.s

vendor/nrfx/drivers/src/nrfx_egu.obj: vendor/nrfx/drivers/src/nrfx_egu.c.obj
.PHONY : vendor/nrfx/drivers/src/nrfx_egu.obj

# target to build an object file
vendor/nrfx/drivers/src/nrfx_egu.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/vendor/nrfx/drivers/src/nrfx_egu.c.obj
.PHONY : vendor/nrfx/drivers/src/nrfx_egu.c.obj

vendor/nrfx/drivers/src/nrfx_egu.i: vendor/nrfx/drivers/src/nrfx_egu.c.i
.PHONY : vendor/nrfx/drivers/src/nrfx_egu.i

# target to preprocess a source file
vendor/nrfx/drivers/src/nrfx_egu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/vendor/nrfx/drivers/src/nrfx_egu.c.i
.PHONY : vendor/nrfx/drivers/src/nrfx_egu.c.i

vendor/nrfx/drivers/src/nrfx_egu.s: vendor/nrfx/drivers/src/nrfx_egu.c.s
.PHONY : vendor/nrfx/drivers/src/nrfx_egu.s

# target to generate assembly for a file
vendor/nrfx/drivers/src/nrfx_egu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/vendor/nrfx/drivers/src/nrfx_egu.c.s
.PHONY : vendor/nrfx/drivers/src/nrfx_egu.c.s

vendor/nrfx/drivers/src/nrfx_timer.obj: vendor/nrfx/drivers/src/nrfx_timer.c.obj
.PHONY : vendor/nrfx/drivers/src/nrfx_timer.obj

# target to build an object file
vendor/nrfx/drivers/src/nrfx_timer.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/vendor/nrfx/drivers/src/nrfx_timer.c.obj
.PHONY : vendor/nrfx/drivers/src/nrfx_timer.c.obj

vendor/nrfx/drivers/src/nrfx_timer.i: vendor/nrfx/drivers/src/nrfx_timer.c.i
.PHONY : vendor/nrfx/drivers/src/nrfx_timer.i

# target to preprocess a source file
vendor/nrfx/drivers/src/nrfx_timer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/vendor/nrfx/drivers/src/nrfx_timer.c.i
.PHONY : vendor/nrfx/drivers/src/nrfx_timer.c.i

vendor/nrfx/drivers/src/nrfx_timer.s: vendor/nrfx/drivers/src/nrfx_timer.c.s
.PHONY : vendor/nrfx/drivers/src/nrfx_timer.s

# target to generate assembly for a file
vendor/nrfx/drivers/src/nrfx_timer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf52-ao.elf.dir/build.make CMakeFiles/nrf52-ao.elf.dir/vendor/nrfx/drivers/src/nrfx_timer.c.s
.PHONY : vendor/nrfx/drivers/src/nrfx_timer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rust_app_build"
	@echo "... nrf52-ao.elf"
	@echo "... c/src/hw_egu.obj"
	@echo "... c/src/hw_egu.i"
	@echo "... c/src/hw_egu.s"
	@echo "... c/src/hw_gpio.obj"
	@echo "... c/src/hw_gpio.i"
	@echo "... c/src/hw_gpio.s"
	@echo "... c/src/hw_timer.obj"
	@echo "... c/src/hw_timer.i"
	@echo "... c/src/hw_timer.s"
	@echo "... c/src/isr_mask.obj"
	@echo "... c/src/isr_mask.i"
	@echo "... c/src/isr_mask.s"
	@echo "... c/src/main.obj"
	@echo "... c/src/main.i"
	@echo "... c/src/main.s"
	@echo "... vendor/nrfx/bsp/stable/mdk/gcc_startup_nrf52840.obj"
	@echo "... vendor/nrfx/bsp/stable/mdk/system_nrf52840.obj"
	@echo "... vendor/nrfx/bsp/stable/mdk/system_nrf52840.i"
	@echo "... vendor/nrfx/bsp/stable/mdk/system_nrf52840.s"
	@echo "... vendor/nrfx/drivers/src/nrfx_egu.obj"
	@echo "... vendor/nrfx/drivers/src/nrfx_egu.i"
	@echo "... vendor/nrfx/drivers/src/nrfx_egu.s"
	@echo "... vendor/nrfx/drivers/src/nrfx_timer.obj"
	@echo "... vendor/nrfx/drivers/src/nrfx_timer.i"
	@echo "... vendor/nrfx/drivers/src/nrfx_timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/ms/elec/birdscanner/nrf52-ao/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
